// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IVault is an autogenerated mock type for the IVault type
type IVault struct {
	mock.Mock
}

// Getk8sServiceAccountToken provides a mock function with given fields:
func (_m *IVault) Getk8sServiceAccountToken() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WaitForVaultToUnseal provides a mock function with given fields: url, wait, retry
func (_m *IVault) WaitForVaultToUnseal(url string, wait time.Duration, retry int) error {
	ret := _m.Called(url, wait, retry)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, int) error); ok {
		r0 = rf(url, wait, retry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
