name: Versioning
on:
  push:
    branches: [ci/new-release]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run the tagging script
        run: ./.github/workflows/tag_main_branch.sh ci/new-release
